name: Digest Automation

on:
  push:
    paths:
      - 'digests/**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install openai requests python-dotenv
      - name: Run pipeline
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
          TRANSISTOR_API_KEY: ${{ secrets.TRANSISTOR_API_KEY }}
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: |
          for f in digests/*.md; do
            python scripts/run_pipeline.py "$f"
          done
      - name: Commit outputs
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add outputs metadata
          git commit -m "Automated digest outputs" || echo "No changes"
          git push
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          files: |
            outputs/pdfs/*
            outputs/podcasts/*.mp3
            outputs/social/*.json
            outputs/archive/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
