name: Build-and-Send Digest

on:
  schedule:
    - cron: '05 10 * * *'   # 10:05 UTC = 05:05 CDT
  workflow_dispatch:

env:
  TZ: America/Chicago

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry & deps
        run: |
          pip install poetry
          poetry install --no-root
      - uses: actions/checkout@v4
      - name: Fetch & Summarise
        run: poetry run python src/fetch_summaries.py
      - name: Upload articles
        uses: actions/upload-artifact@v4
        with:
          name: articles-json
          path: output/articles.json

  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry & deps
        run: |
          pip install poetry
          poetry install --no-root
      - uses: actions/checkout@v4
      - name: Download articles
        uses: actions/download-artifact@v4
        with:
          name: articles-json
      - name: Render Digest to PDF
        run: poetry run python src/render_pdf.py
      - name: Upload digest artifacts
        uses: actions/upload-artifact@v4
        with:
          name: digest
          path: output/

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry & deps
        run: |
          pip install poetry
          poetry install --no-root
      - uses: actions/checkout@v4
      - name: Download Digest
        uses: actions/download-artifact@v4
        with:
          name: digest
      - name: Send Digest via Buttondown
        env:
          BUTTONDOWN_TOKEN: ${{ secrets.BUTTONDOWN_TOKEN }}
        run: poetry run python src/send_digest.py
