name: Run Digest Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '1 2 * * *'  # 2:01 AM UTC = 8:01 PM CST

jobs:
  digest:
    runs-on: ubuntu-latest
    env:
      READWISE_TOKEN: ${{ secrets.READWISE_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      BUTTONDOWN_TOKEN: ${{ secrets.BUTTONDOWN_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install requests python-dotenv python-dateutil
      - name: Run digest pipeline
        run: python digest_pipeline.py
