name: Build-and-Send Digest

on:
  schedule:
    - cron: '05 10 * * *'   # runs daily at 05:05 CDT
  workflow_dispatch:       # allows manual trigger

env:
  TZ: America/Chicago

jobs:
  ingest:
    runs-on: ubuntu-latest
    env:
      READWISE_TOKEN: ${{ secrets.READWISE_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base fonts-noto

      - name: Install Poetry & Python deps
        run: |
          pip install poetry
          poetry install --no-root

      - name: Fetch Reader articles
        run: poetry run python src/fetch_summaries.py

      - name: Upload articles-json artifact
        uses: actions/upload-artifact@v4
        with:
          name: articles-json
          path: output/articles.json
          if-no-files-found: error

  render:
    needs: ingest
    runs-on: ubuntu-latest
    env:
      READWISE_TOKEN:   ${{ secrets.READWISE_TOKEN }}
      OPENAI_API_KEY:   ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base fonts-noto

      - name: Install Poetry & Python deps
        run: |
          pip install poetry
          poetry install --no-root

      - name: Download articles-json artifact
        uses: actions/download-artifact@v4
        with:
          name: articles-json
          path: .      # will drop articles.json into workspace root

      - name: Ensure output/articles.json exists
        run: |
          if [ -f output/articles.json ]; then
            echo "✔ output/articles.json in place"
          elif [ -f articles.json ]; then
            mkdir -p output
            mv articles.json output/articles.json
          else
            echo "❌ Missing articles.json" && exit 1
          fi

      - name: Render Digest PDF
        run: poetry run python src/render_pdf.py

      - name: Upload digest artifact
        uses: actions/upload-artifact@v4
        with:
          name: digest
          path: output/digest.pdf
          if-no-files-found: error

  publish:
    needs: render
    runs-on: ubuntu-latest
    env:
      BUTTONDOWN_TOKEN: ${{ secrets.BUTTONDOWN_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base fonts-noto

      - name: Install Poetry & Python deps
        run: |
          pip install poetry
          poetry install --no-root

      - name: Download digest artifact
        uses: actions/download-artifact@v4
        with:
          name: digest
          path: .     # recreates output/digest.pdf

      - name: Send Digest via Buttondown
        run: poetry run python src/send_digest.py
