name: Build-and-Send Digest

on:
  schedule:
    - cron: '05 10 * * *'   # 10:05 UTC = 05:05 CDT
  workflow_dispatch:

env:
  TZ: America/Chicago

jobs:
  ingest:
    runs-on: ubuntu-latest
    env:
      READWISE_TOKEN: ${{ secrets.READWISE_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base fonts-noto

      - name: Install Poetry deps
        run: |
          pip install poetry
          poetry install --no-root

      - name: Fetch last-24h Reader articles
        run: poetry run python src/fetch_summaries.py

      - uses: actions/upload-artifact@v4
        with:
          name: articles-json
          path: output/articles.json

  render:
    runs-on: ubuntu-latest
    env:
      READWISE_TOKEN: ${{ secrets.READWISE_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base fonts-noto
      - run: |
          pip install poetry
          poetry install --no-root
      - uses: actions/download-artifact@v4
        with: { name: articles-json }
      - name: Render Digest PDF
        run: poetry run python src/render_pdf.py
      - uses: actions/upload-artifact@v4
        with:
          name: digest
          path: output/

  publish:
    runs-on: ubuntu-latest
    env:
      READWISE_TOKEN: ${{ secrets.READWISE_TOKEN }}
      BUTTONDOWN_TOKEN: ${{ secrets.BUTTONDOWN_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base fonts-noto
      - run: |
          pip install poetry
          poetry install --no-root
      - uses: actions/download-artifact@v4
        with: { name: digest }
      - name: Send digest via Buttondown
        run: poetry run python src/send_digest.py
