name: Build-and-Send Digest

on:
  schedule:
    - cron: '05 10 * * *'   # 10:05 UTC = 05:05 CDT
  workflow_dispatch:

env:
  TZ: America/Chicago

jobs:
# ── Ingest ────────────────────────────────────────────────────────────
  ingest:
    runs-on: ubuntu-latest
    env:
      READWISE_TOKEN: ${{ secrets.READWISE_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Sys deps
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base fonts-noto

      - name: Python deps
        run: |
          pip install poetry
          poetry install --no-root

      - name: Fetch Reader articles
        run: poetry run python src/fetch_summaries.py

      - name: Upload output/ folder
        uses: actions/upload-artifact@v4
        with:
          name: articles-json
          path: output     # <── keeps output/articles.json inside

# ── Render ────────────────────────────────────────────────────────────
  render:
    needs: ingest
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Sys deps
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base fonts-noto

      - name: Python deps
        run: |
          pip install poetry
          poetry install --no-root

      - name: Download output/ folder
        uses: actions/download-artifact@v4
        with:
          name: articles-json
          path: .           # recreates output/articles.json

      - name: Render PDF
        run: poetry run python src/render_pdf.py

      - name: Upload output/ folder (PDF inside)
        uses: actions/upload-artifact@v4
        with:
          name: digest
          path: output      # includes output/digest.pdf

# ── Publish ───────────────────────────────────────────────────────────
  publish:
    needs: render
    runs-on: ubuntu-latest
    env:
      BUTTONDOWN_TOKEN: ${{ secrets.BUTTONDOWN_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Sys deps
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base fonts-noto

      - name: Python deps
        run: |
          pip install poetry
          poetry install --no-root

      - name: Download output/ folder (PDF)
        uses: actions/download-artifact@v4
        with:
          name: digest
          path: .           # recreates output/digest.pdf

      - name: Send Digest
        run: poetry run python src/send_digest.py
