name: Build-and-Send Digest

on:
  schedule:
    - cron: '05 10 * * *'   # 10:05 UTC = 05:05 CDT
  workflow_dispatch:

env:
  TZ: America/Chicago

jobs:
  ingest:
    runs-on: ubuntu-latest
    env:
      READWISE_TOKEN: ${{ secrets.READWISE_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base fonts-noto

      - name: Install Poetry & Python deps
        run: |
          pip install poetry
          poetry install --no-root

      - name: Fetch last-24h Reader articles
        run: poetry run python src/fetch_summaries.py

      - name: Upload raw articles artifact
        uses: actions/upload-artifact@v4
        with:
          name: articles-json
          path: output/articles.json

  render:
    needs: ingest
    runs-on: ubuntu-latest
    env:
      READWISE_TOKEN: ${{ secrets.READWISE_TOKEN }}
      OPENAI_API_KEY:   ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base fonts-noto

      - name: Install Poetry & Python deps
        run: |
          pip install poetry
          poetry install --no-root

      - name: Download raw articles artifact
        uses: actions/download-artifact@v4
        with:
          name: articles-json
          path: .    # writes output/articles.json to workspace

      - name: Render Digest to PDF
        run: poetry run python src/render_pdf.py

      - name: Upload PDF digest artifact
        uses: actions/upload-artifact@v4
        with:
          name: digest
          path: output/digest.pdf

  publish:
    needs: render
    runs-on: ubuntu-latest
    env:
      BUTTONDOWN_TOKEN: ${{ secrets.BUTTONDOWN_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base fonts-noto

      - name: Install Poetry & Python deps
        run: |
          pip install poetry
          poetry install --no-root

      - name: Download PDF digest artifact
        uses: actions/download-artifact@v4
        with:
          name: digest
          path: .    # writes output/digest.pdf to workspace

      - name: Send Digest via Buttondown
        run: poetry run python src/send_digest.py
