name: Ohmbudsman Digest

on:
  schedule:
    - cron: "05 10 * * *"   # daily at 05:05 CDT
  workflow_dispatch:

permissions:
  contents: write         # needed to push to gh-pages

jobs:
  ingest:
    runs-on: ubuntu-latest
    env:
      READWISE_TOKEN: ${{ secrets.READWISE_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pandoc texlive-latex-base texlive-latex-extra \
            texlive-xetex fonts-noto

      - name: Install Poetry deps
        run: |
          pip install poetry
          poetry install --no-root

      - name: Generate Markdown Digest
        run: poetry run python src/generate_digest.py

      - name: Upload markdown artifact
        uses: actions/upload-artifact@v4
        with:
          name: markdown
          path: output/digest_output.md
          if-no-files-found: error

  render:
    needs: ingest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pandoc texlive-latex-base texlive-latex-extra \
            texlive-xetex fonts-noto git

      - name: Install Poetry deps
        run: |
          pip install poetry
          poetry install --no-root

      - name: Download markdown artifact
        uses: actions/download-artifact@v4
        with:
          name: markdown
          path: .

      - name: Normalize markdown path
        run: |
          if [ -f digest_output.md ]; then
            mkdir -p output
            mv digest_output.md output/digest_output.md
          fi
          if [ ! -f output/digest_output.md ]; then
            echo "❌ Missing output/digest_output.md" && exit 1
          fi

      - name: Render PDF
        run: poetry run python src/render_pdf.py

      - name: Push PDF to gh-pages
        run: |
          BRANCH=gh-pages
          PDF_NAME=$(date +'%Y-%m-%d').pdf
          git config --global user.email "ci@github"
          git config --global user.name  "ci-bot"
          git fetch origin $BRANCH || git branch $BRANCH
          git switch $BRANCH
          mkdir -p digests
          cp output/digest.pdf digests/$PDF_NAME
          git add digests/$PDF_NAME
          git commit -m "Add $PDF_NAME (run $GITHUB_RUN_ID)" || echo "No changes"
          git push origin $BRANCH

  publish:
    needs: render
    runs-on: ubuntu-latest
    env:
      BUTTONDOWN_TOKEN: ${{ secrets.BUTTONDOWN_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry deps
        run: |
          pip install poetry
          poetry install --no-root

      - name: Download markdown artifact
        uses: actions/download-artifact@v4
        with:
          name: markdown
          path: .

      - name: Normalize markdown path for publish
        run: |
          if [ -f digest_output.md ]; then
            mkdir -p output
            mv digest_output.md output/digest_output.md
          fi

      - name: Create Buttondown draft
        run: poetry run python src/send_digest.py
